

freebsd_instance:
  image_family: freebsd-12-1

# Adapted from https://github.com/Stebalien/xattr

task:
  name: cargo test
  # Record some info about the test environment
  sysinfo_script:
    - mount
    - df -h
    - sysctl hw.model hw.ncpu hw.physmem
    - freebsd-version
  # Install Rust
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
    - rustc --version
  test_script:
    - . $HOME/.cargo/env
    - cargo test
    - cargo build
