name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, ubuntu-20.04]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies (macOS)
      run: brew install shunit2 shellcheck shfmt
      if: runner.os == 'macOS'
    - name: Install dependencies (Linux)
      run: sudo apt-get -y install libacl1-dev acl shunit2 valgrind shellcheck
      if: runner.os == 'Linux'
    - name: Build
      run: cargo build
    - name: Run unit tests
      run: cargo test
    - name: Run integration tests
      run: ./tests/run_tests.sh
    - name: Run memory tests (Linux)
      run: ./tests/run_tests.sh memcheck
      if: runner.os == 'Linux'
    - name: Code coverage
      run: ./ci/coverage.sh codecov
    - name: Lint Check
      run: ./ci/lint.sh
    - name: Format Check
      run: ./ci/format.sh
    - name: Docs Check
      run: ./ci/docs.sh
