name: Publish Docs

on:
  push:
    branches: [ "*" ]
#  pull_request:
#    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-docs:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies (Linux)
      run: sudo apt-get -y install libacl1-dev
    - name: Build Docs
      run: ./ci/docs.sh
    - name: Publish Docs to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
