name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies (macOS)
      run: brew install shunit2 shellcheck
      if: runner.os == 'macOS'
    - name: Install dependencies (Linux)
      run: sudo apt-get -y install libacl1-dev shunit2 valgrind shellcheck
      if: runner.os == 'Linux'
    - name: Build
      run: cargo build
    - name: Run unit tests
      run: cargo test
    - name: Run integration tests
      run: ./tests/run_tests.sh
    - name: Run memory tests (Linux)
      run: ./tests/run_tests.sh memcheck
      if: runner.os == 'Linux'
    - name: Code coverage
      run: ./ci/coverage.sh codecov
    - name: Build docs
      run: ./ci/docs.sh
    - name: Lint Check
      run: ./ci/lint.sh
    - name: Format Check
      run: cargo fmt -- --check
