name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies (macOS)
      run: brew install shunit2
      if: runner.os == 'macOS'
    - name: Install dependencies (Linux)
      run: sudo apt-get -y install libacl1-dev shunit2
      if: runner.os == 'Linux'
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --verbose
    - name: Run integration tests
      run: ./tests/run_tests.sh
    - name: Code coverage
      run: ./ci/code_coverage.sh codecov
    - name: Build docs (Linux)
      run: ./ci/build_docs.sh
      if: runner.os == 'Linux'

